export const customStyles = {
  control: (provided, state) => ({
    ...provided,
    backgroundColor: "transparent",
    fontFamily: "var(--font-family)",
    fontWeight: 400,
    color: "var(--primary)",
    display: "flex",
    border: "none",
    boxShadow: state.isFocused ? "none" : "none",
    cursor: "pointer",
    "&:hover": {
      // border: 'none',
      boxShadow: "none",
    },
    "&:focus": {
      // border: 'none',
      outline: "none",
      boxShadow: "none",
    },
    "&:active": {
      // border: 'none',
      outline: "none",
      boxShadow: "none",
    },
  }),
  menu: (provided) => ({
    ...provided,
    padding: 0,
    width: 130,
    boxSizing: "contain",
    left: "50%",
    transform: "translate(-50%, -5px)",
    border: "1px solid #ccc",
    borderRadius: 8,
  }),
  menuList: (provided) => ({
    ...provided,
    padding: 0,
    width: 130,
    borderRadius: 8,
  }),
  valueContainer: (provided) => ({
    ...provided,
    padding: 0,
  }),
  indicatorSeparator: () => ({ display: "none" }),
  dropdownIndicator: (provided) => ({
    ...provided,
    color: "var(--primary)",
    padding: 0,
    "&:hover": {
      color: "var(--primary)",
      cursor: "pointer",
    },
  }),
  singleValue: (provided) => ({
    ...provided,
    display: "flex",
    alignItems: "center",
    padding: 0,
    cursor: "pointer",
    color: "var(--primary)",
  }),
  option: (provided, state) => ({
    ...provided,
    cursor: "pointer",
    fontFamily: "var(--font-family)",
    fontWeight: 400,
    boxSizing: "border-box",
    width: 130,
    backgroundColor: state.isSelected ? "var(--secondary)" : "var(--primary)",
    "&:hover": {
      color: "var(--primary)",
      backgroundColor: "var(--secondary)",
      cursor: "pointer",
    },
  }),
};
